/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Motor_PWM.h"
#include "Clock_1.h"
#include "Motor_1_aliases.h"
#include "Motor_1.h"
#include "Motor_2_aliases.h"
#include "Motor_2.h"
#include "isr_uart_rx.h"
#include "UART_1.h"
#include "Clock_2.h"
#include "isr_pid.h"
#include "Counter_Sensor.h"
#include "Clock_3.h"
#include "Sensor_Input_aliases.h"
#include "Sensor_Input.h"
#include "sensor_input_isr.h"
#include "Clock_4.h"
#include "Sensor_Out.h"
#include "Clock_5.h"
#include "Sensor_Out_Pin_1_aliases.h"
#include "Sensor_Out_Pin_1.h"
#include "Sensor_Out_Pin_2_aliases.h"
#include "Sensor_Out_Pin_2.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

